#!/bin/bash
#
# Loops over annotated calls and write out pass-only VCFs

module load tabix/0.2.6

readonly OUTDIR=./passonly
readonly INDIR=./annotated
readonly BLACKLIST=../filters/blacklist/final_blacklist.txt
readonly INCOMPLETE=../filters/incomplete/incomplete.txt
readonly GRAYLIST=../filters/graylist/graylist.txt
readonly BADLIST=badlist.txt

cat ${BLACKLIST} ${INCOMPLETE} | sort -u > ${BADLIST}

mkdir -p "$OUTDIR"

function drop_some_headers {
    grep -v "ID=OXOG_Fail" \
      | grep -v "ID=dbsnp_VP"
}

function header_or_pass {
    awk '$1 ~ /^#/ || $7 == "."'
}

for variant in "snv_mnv" "indel"
do
    mkdir -p ${OUTDIR}/${variant}
    files=$( ls ${INDIR}/${variant}/*.${variant}.vcf.gz | grep -vf ${BADLIST} )
    for file in ${files}
    do
        base=$( basename $file )
        id=$( echo $base | cut -f 1 -d . )
        echo "${id} ${variant}"
        out=${OUTDIR}/${variant}/${base}
        if [[ ! -f "$out" ]] || [[ "$file" -nt "$out" ]]
        then
            zcat $file \
                | header_or_pass \
                | drop_some_headers \
                | bgzip \
                > ${out}
            tabix -p vcf ${out}
        fi
    done
    files=$( ls ${OUTDIR}/${variant}/*.vcf.gz* | grep -f ${GRAYLIST} )
    mkdir -p ${OUTDIR}/graylist/${variant}
    for file in ${files}
    do
        mv ${file} ${OUTDIR}/graylist/${variant}
    done
done
